{% set name = "aicsimageio" %}
{% set version = "4.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f6684587b1d833ce5b10f3e81314e2a89269cd94bd09747fcd6460f3119855c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .[all] -vv

requirements:
  host:
    - python >=3.8
    - pip
    - pytest-runner >=5.2
    - setuptools
  run:
    - python >=3.8
    - dask >=2021.4.1,<=2023.5.0
    - fsspec >=2022.8.0,<2023.9.0
    - imagecodecs >=2020.5.30
    - lxml >=4.6,<5
    - numpy >=1.16,<=1.24.0
    - ome-types >=0.3.4
    - ome-zarr >=0.6.1
    - resource_backed_dask_array >=0.1.0
    # Reduced the upper limit to support the bfio extra
    - tifffile >=2021.8.30,<2022.4.22
    - wrapt >=1.12
    - xarray >=0.16.1,<2023.02.0
    - xmlschema
    - zarr >=2.6,<2.16.0

    # Extra Formats (included by default)
    # base-imageio
    - imageio >=2.11.0,<2.28.0
    - imageio-ffmpeg
    - psutil >=5.7.0
    # "nd2"
    - nd2[legacy] >=0.6.0
    # "dv"
    - mrc >=0.2.0
    # "bfio"
    - bfio ==2.3.0

  run_constrained:
    # We don't depend on scikit-image directly, but without this constraint, we get:
    # "scikit-image 0.24.0 has requirement imageio>=2.33, but you have imageio 2.27.0."
    # This is not in the pyproject.toml for 4.12.0
    - scikit-image <0.23

test:
  requires:
    - pip
  imports:
    - aicsimageio
  commands:
    - pip list
    - pip check

about:
  home: https://github.com/AllenCellModeling/aicsimageio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image Reading, Metadata Conversion, and Image Writing for Microscopy Images in Pure Python
  doc_url: https://allencellmodeling.github.io/aicsimageio/index.html
  dev_url: https://github.com/AllenCellModeling/aicsimageio

extra:
  recipe-maintainers:
    - SeanLeRoy
    - evamaxfield
    - toloudis
    - tlambert03
