{% set name = "aicsimageio" %}
{% set version = "4.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdb21b4e17f4a083704f74e97d0f32b2f601084ff6e89de3316ced45e2ec5967

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - pytest-runner >=5.2
  run:
    - python >=3.8
    - dask >=2021.4.1
    - fsspec >=2022.8.0
    - imagecodecs >=2020.5.30
    - lxml >=4.6
    - numpy >=1.16
    - ome-types >=0.3.3
    - ome-zarr >=0.6.1
    - resource_backed_dask_array >=0.1.0
    - tifffile >=2021.8.30,<2023.3.15
    - wrapt >=1.12
    - xarray >=0.16.1,<2023.02.0
    - xmlschema
    - zarr >=2.6

    # Extra Formats (included by default)
    # [base-imageio]
    - imageio
    - imageio-ffmpeg
    - psutil


test:
  requires:
    - pip
  imports:
    - aicsimageio
  commands:
    - pip list
    - pip check

about:
  home: https://github.com/AllenCellModeling/aicsimageio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image Reading, Metadata Conversion, and Image Writing for Microscopy Images in Pure Python
  doc_url: https://allencellmodeling.github.io/aicsimageio/index.html
  dev_url: https://github.com/AllenCellModeling/aicsimageio

extra:
  recipe-maintainers:
    - evamaxfield
    - toloudis
    - tlambert03
